#CC = g++
#CFLAGS = -std=c++11 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm

#all: da1

#da1: main.o vector.o
#	$(CC) $(CFLAGS) main.o vector.o -o da1

#main.o: main.cpp
#	$(CC) $(FLAGS) main.cpp

#vector.o: vector.cpp
#	$(CC) $(FLAGS) vector.cpp

#clean:
#	rm -rf *.o da1

#quick
all:
	g++ -std=c++11 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm main.cpp vector.cpp sort.cpp -o da1
